### ISSUE TITLE
Automate configuration apply using external script 

### ISSUE THREAD

**Issue by mhenphyz** [tacacsgui/tacacsgui#91]
Hi, this is a question about a way to automate the apply button, I created a python script to integrate one of our internal systems to tacgui, I already have a way to create the data inside the database, but every time that we update the database we need to enters in tacacs and click in Test and Apply buttons, maybe I could use a headless browser, but I would like to know if there is an easier way to automate these actions.

**Comment by gurkin33** [comment]
Hello, 
Test and Apply buttons required because they create tac_plus.cfg for test and if it is OK, they apply it as main config. Database uses only to store data, but tac_plus daemon uses text based configuration. TACACSGUI store and create configuration for tac_plus :) If you have script, then you can send API request to apply config, for example, link from test environment:
https://demo.tacacsgui.com:4443/api/tacacs/config/apply/?contentType=json&confTest=on&confSave=yes&doBackup=0
Hope it helps.
Regards, Alexey

**Comment by mhenphyz** [comment]
Oh good, it will help a lot but it is asking for a token to authenticate, I created a user and password, but I didn't found a way to create a token, how can I create it, and what is the parameters that I need to send at the request to have access to API? I tried to find it in the documentation, but there is nothing talking about API.

**Comment by gurkin33** [comment]
It uses JWT token authentication.
After SignIn (/api/auth/signin/) you get token (in response). You should add this token as Header Attribute, for example, I have token _eyJ0eXAiOiJKV1QiLCJ..._ then I will add this attribute to header in every request - _Authorization: Bearer eyJ0eXAiOiJKV1QiLCJ..._

**Comment by mhenphyz** [comment]
It's worked, thanks a lot @gurkin33
